import { readFile, writeFile } from 'node:fs/promises';
const root = new URL('../', import.meta.url);
const files = ['attendance-core.js', 'dashboard.js', 'grabber.js'];
const sources = await Promise.all(files.map(name => readFile(new URL('src/bookmarklet/' + name, root), 'utf8')));
const css = await readFile(new URL('src/bookmarklet/dashboard.css', root), 'utf8');
sources[1] = sources[1].replace('"__VTC_DASHBOARD_CSS__"', JSON.stringify(css));
await writeFile(new URL('src/bookmarklet/vtc-combined-grabber.js', root), '// Generated by node scripts/build.mjs. Edit the source files, then rebuild.\n' + sources.join('\n'));
console.log('Built standalone bookmarklet.');
